# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cff2ae7458fd5804cb6d4b12efa9b506b742316c1e93f18db144ad66bcb0552c142ebcfbf9745437a0f73bf9185b7856a7e95fab57cafa9b4db0804486122e7

test:
  secret_key_base: 311ec5daac2dfc8471aade3db554f89254277c20095629708e180b36b6044eb0cbee1a3092fdcc8b5d1521c8aed83e5fcdebf8e9a382ea51b8875593a2f3e574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
